// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordSearchingGameAPI.Models;

public partial class Word
{
    public int WordId { get; set; }

    public string Word1 { get; set; }

    public int? TopicId { get; set; }

    public int? DifficultyId { get; set; }

    public virtual Difficulty Difficulty { get; set; }

    public virtual Topic Topic { get; set; }
}